// packages/app/src/routes/NetworkCheck.tsx
import { type Component, For, Show, createSignal, onCleanup, onSettled } from "solid-js";
import {
  evaluate,
  formatReport,
  type DiagCheckView,
  type DiagInput,
  type DiagReport,
  type DiagStatus,
} from "@pictelio/net-diagnostics";
import PageTransition from "../components/PageTransition";
import { goBack } from "../services/backTransitionService";
import { collectNetDiagInput } from "../native/NetDiag";
import { user } from "../stores/authStore";

const STATUS_LABEL: Record<DiagStatus, string> = {
  ok: "通过",
  warn: "注意",
  fail: "失败",
  skipped: "跳过",
};
const STATUS_COLOR: Record<DiagStatus, string> = {
  ok: "var(--colorStatusSuccessForeground1)",
  warn: "var(--colorStatusWarningForeground1)",
  fail: "var(--colorStatusDangerForeground1)",
  skipped: "var(--colorNeutralForeground3)",
};

/**
 * 网络自检页（spec docs/specs/network-self-check.md）。
 * 一键运行 -> 逐项绿/黄/红 + 结论/归因 -> 复制脱敏报告。判定在 @pictelio/net-diagnostics。
 */
const NetworkCheck: Component = () => {
  const [input, setInput] = createSignal<DiagInput | null>(null);
  const [report, setReport] = createSignal<DiagReport | null>(null);
  const [running, setRunning] = createSignal(false);
  const [copied, setCopied] = createSignal(false);
  let alive = true;
  onCleanup(() => {
    alive = false;
  });

  async function run() {
    if (running()) return;
    setRunning(true);
    setCopied(false);
    try {
      const uid = user()?.id;
      const inp = await collectNetDiagInput(
        APP_VERSION,
        uid === undefined ? undefined : String(uid),
      );
      if (!alive) return;
      setInput(inp);
      setReport(evaluate(inp));
    } catch (e) {
      console.warn("[network-check] 自检失败:", e);
      if (alive) {
        const fallback: DiagInput = {
          platform: "android",
          engine: "webview",
          appVersion: APP_VERSION,
          probes: [],
          degraded: true,
          capturedAt: new Date().toISOString(),
        };
        setInput(fallback);
        setReport(evaluate(fallback));
      }
    } finally {
      if (alive) setRunning(false);
    }
  }

  onSettled(() => {
    void run();
  });

  async function copyReport() {
    const inp = input();
    if (!inp) return;
    try {
      await navigator.clipboard.writeText(formatReport(inp));
      setCopied(true);
    } catch (e) {
      console.warn("[network-check] 复制报告失败:", e);
    }
  }

  return (
    <PageTransition>
      <div class="page">
        <div class="flex items-center gap-3 p-4 border-b border-[var(--colorNeutralStroke2)]">
          <button
            class="text-[var(--colorNeutralForeground2)] hover:text-[var(--colorNeutralForeground1)] p-1 -ml-1 min-w-[40px] min-h-[40px] flex items-center justify-center focus-visible:outline-2 focus-visible:outline-[var(--colorStrokeFocus2)] focus-visible:outline-offset-2"
            onClick={() => goBack()}
            aria-label="返回"
          >
            ←
          </button>
          <h1 class="text-[var(--fontSizeHero700)] font-semibold text-[var(--colorNeutralForeground1)]">
            网络自检
          </h1>
        </div>

        <div class="p-4 space-y-4">
          <Show
            when={report()}
            fallback={
              <div class="surface-flyout p-4 text-[var(--fontSizeBase300)] text-[var(--colorNeutralForeground3)]">
                正在自检…
              </div>
            }
          >
            {(rep) => (
              <>
                <div class="surface-flyout p-4">
                  <p
                    class="text-[var(--fontSizeBase400)] font-semibold"
                    style={{ color: STATUS_COLOR[rep().overall] }}
                  >
                    {rep().headline}
                  </p>
                  <Show when={rep().degraded}>
                    <p class="mt-1 text-[var(--fontSizeBase200)] text-[var(--colorNeutralForeground3)]">
                      开发态降级执行器：仅覆盖部分检查项，结论不代表真机完整能力。
                    </p>
                  </Show>
                  <Show when={rep().action}>
                    <p class="mt-1 text-[var(--fontSizeBase300)] text-[var(--colorNeutralForeground2)]">
                      建议：{rep().action}
                    </p>
                  </Show>
                </div>

                <div class="surface-flyout p-4">
                  <For each={rep().checks}>
                    {(c: DiagCheckView) => (
                      <div class="flex items-start gap-2 py-2 border-b border-[var(--colorNeutralStroke2)] last:border-b-0">
                        <span
                          class="shrink-0 text-[var(--fontSizeBase200)] font-semibold pt-0.5"
                          style={{ color: STATUS_COLOR[c.status] }}
                        >
                          [{STATUS_LABEL[c.status]}]
                        </span>
                        <div class="min-w-0">
                          <p class="text-[var(--fontSizeBase300)] text-[var(--colorNeutralForeground1)]">
                            {c.title}
                            {c.latencyMs !== undefined ? " · " + c.latencyMs + "ms" : ""}
                          </p>
                          <p class="text-[var(--fontSizeBase200)] text-[var(--colorNeutralForeground3)] leading-snug">
                            {c.detail}
                          </p>
                          <Show when={c.hint}>
                            <p class="text-[var(--fontSizeBase200)] text-[var(--colorNeutralForeground2)] leading-snug">
                              {c.hint}
                            </p>
                          </Show>
                        </div>
                      </div>
                    )}
                  </For>
                </div>
              </>
            )}
          </Show>

          <div class="flex gap-2">
            <button
              class="flex-1 min-h-[40px] rounded-[var(--borderRadiusMedium)] bg-[var(--colorBrandBackground)] text-[var(--colorNeutralForegroundOnBrand)] [font-size:var(--fontSizeBase300)] font-semibold active:scale-[0.98] transition-transform duration-[var(--durationFast)] disabled:opacity-50"
              onClick={() => void run()}
              disabled={running()}
            >
              {running() ? "自检中…" : "重新自检"}
            </button>
            <button
              class="flex-1 min-h-[40px] rounded-[var(--borderRadiusMedium)] bg-[var(--colorNeutralBackground3)] text-[var(--colorNeutralForeground1)] [font-size:var(--fontSizeBase300)] font-semibold active:scale-[0.98] transition-transform duration-[var(--durationFast)] disabled:opacity-50"
              onClick={() => void copyReport()}
              disabled={!input()}
            >
              {copied() ? "已复制" : "复制报告"}
            </button>
          </div>
        </div>
      </div>
    </PageTransition>
  );
};

export default NetworkCheck;

// packages/app-lynx/src/pages/NetworkCheck.vue
<script setup lang="ts">
// [lynx:fix] KeepAlive include 匹配需要组件 name（ADR-0049）
defineOptions({ name: 'network-check' })
import { ref } from 'vue'
import { evaluate, formatReport, type DiagInput, type DiagReport, type DiagStatus } from '@pictelio/net-diagnostics'
import { collectNetDiagInput } from '../utils/netDiagnostics'
import { useAuthStore } from '../stores/authStore'
import { goBack } from '../router'

const auth = useAuthStore()
const report = ref<DiagReport | null>(null)
const input = ref<DiagInput | null>(null)
const running = ref(false)
const copied = ref(false)

const STATUS_LABEL: Record<DiagStatus, string> = { ok: '通过', warn: '注意', fail: '失败', skipped: '跳过' }
const STATUS_CLASS: Record<DiagStatus, string> = {
  ok: 'text-success',
  warn: 'text-warning',
  fail: 'text-error',
  skipped: 'text-outline',
}

async function run() {
  if (running.value) return
  running.value = true
  copied.value = false
  try {
    const uid = auth.currentUser?.id
    const inp = await collectNetDiagInput(__APP_VERSION__, uid === undefined ? undefined : String(uid))
    input.value = inp
    report.value = evaluate(inp)
  } catch (e) {
    console.warn('[network-check] 自检失败:', e)
    const fallback: DiagInput = {
      platform: 'android',
      engine: 'lynx',
      appVersion: __APP_VERSION__,
      probes: [],
      degraded: true,
      capturedAt: new Date().toISOString(),
    }
    input.value = fallback
    report.value = evaluate(fallback)
  } finally {
    running.value = false
  }
}

async function copyReport() {
  if (!input.value) return
  try {
    const nav = globalThis.navigator as
      | { clipboard?: { writeText?: (t: string) => Promise<void> } }
      | undefined
    await nav?.clipboard?.writeText?.(formatReport(input.value))
    copied.value = true
  } catch (e) {
    console.warn('[network-check] 复制失败:', e)
  }
}

void run()
</script>

<!--
  网络自检页（spec docs/specs/network-self-check.md）：判定/文案/报告来自共享包
  @pictelio/net-diagnostics，本页只渲染 + 触发探测（NativeModule，web-core 降级）。
-->
<template>
  <view class="w-full h-full flex flex-col bg-surface">
    <view class="flex flex-row items-center h-[17.067vw] px-4 bg-surface">
      <view class="py-1 pr-2" @tap="goBack()">
        <text class="text-label-large text-primary pr-4">返回</text>
      </view>
      <text class="flex-1 text-title-large font-medium text-surface-on">网络自检</text>
    </view>

    <scroll-view scroll-orientation="vertical" class="w-full flex-1 px-4">
      <view class="bg-surface-container-lowest mt-[4vw] p-4 rounded-[var(--md-shape-medium)] shadow-[var(--md-elevation-1)] flex flex-col">
        <text v-if="report" :class="'text-title-medium font-medium ' + STATUS_CLASS[report.overall]">{{ report.headline }}</text>
        <text v-else class="text-body-medium text-outline">正在自检…</text>
        <text v-if="report?.degraded" class="text-body-small text-outline mt-1">开发态降级：仅覆盖部分检查项</text>
        <text v-if="report?.action" class="text-body-small text-surface-on-variant mt-1">建议：{{ report.action }}</text>
      </view>

      <view
        v-if="report"
        class="bg-surface-container-lowest mt-3 p-4 rounded-[var(--md-shape-medium)] shadow-[var(--md-elevation-1)] flex flex-col"
      >
        <view v-for="c in report.checks" :key="c.id" class="py-2 flex flex-col">
          <text class="text-title-small text-surface-on">
            <text :class="STATUS_CLASS[c.status]">[{{ STATUS_LABEL[c.status] }}] </text>{{ c.title }}<text v-if="c.latencyMs !== undefined"> · {{ c.latencyMs }}ms</text>
          </text>
          <text class="text-body-small text-surface-on-variant leading-snug">{{ c.detail }}</text>
          <text v-if="c.hint" class="text-body-small text-outline leading-snug">{{ c.hint }}</text>
        </view>
      </view>

      <view
        class="mt-[6vw] h-[10.667vw] bg-primary active:bg-state-pressed-primary rounded-[var(--md-shape-full)] flex items-center justify-center"
        @tap="run()"
      >
        <text class="text-label-large text-primary-on font-medium">{{ running ? '自检中…' : '重新自检' }}</text>
      </view>
      <view
        class="mt-3 h-[10.667vw] bg-surface-container-high rounded-[var(--md-shape-full)] flex items-center justify-center"
        @tap="copyReport()"
      >
        <text class="text-label-large text-surface-on font-medium">{{ copied ? '已复制' : '复制诊断报告' }}</text>
      </view>
      <view class="h-[8vw]" />
    </scroll-view>
  </view>
</template>
